config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  resources :products do
    resources :orders, only: :create 
  end
  
  resources :products do
    resources :comments, only: [:create, :show]
  end
  
  resources :orders, only: :index do
    collection do
      get 'clean'
    end
  end
  
  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders

  def self.get_total
    pluck("price * quantity").sum()
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true

  scope :cart, -> {where(payed: false)}

  def self.get_total
    pluck("price * quantity").sum()
  end

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orders
    has_many :users, through: :orders
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :billings
  has_many :products, through: :orders
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
    before_action :authenticate_user!
    def index
        @billings = current_user.billings
    end
    def pre_pay
        orders = current_user.orders.where(payed: false)
        total = orders.pluck("price * quantity").sum()
        items = get_items_hash(orders)
        
        if Rails.env.development?
            redirect_urls_ok = {
                return_url: execute_billings_url,
                cancel_url: "http://localhost:3000/"  
            }
        else
            redirect_urls_ok = {
                return_url: "https://novaparts.herokuapp.com/billings/execute",
                cancel_url: "https://novaparts.herokuapp.com/" 
            }
        end
        
        payment = PayPal::SDK::REST::Payment.new({
            intent: "sale",
            payer: {payment_method: "paypal" },
            redirect_urls: redirect_urls_ok,
            transactions: [{
                item_list: {items: items },
                amount: {total: total.to_s, currency: "USD" },
                description: "Compra desde E-commerce Rails." 
            }]
        })

        if payment.create
            redirect_url = payment.links.find{|v| v.method == "REDIRECT"}.href
            redirect_to redirect_url
        else
            render json: payment.error
        end
    end

    def execute
        paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
        if paypal_payment.execute(payer_id: params[:PayerID])
            amount = paypal_payment.transactions.first.amount.total
            billing = Billing.create(
                user: current_user,
                code: paypal_payment.id,
                payment_method: 'paypal',
                amount: amount,
                currency: 'USD'
            )
            orders = current_user.orders.where(payed: false)
            orders.update_all(payed: true, billing_id: billing.id)
            redirect_to root_path, notice: "La compra se realizó con éxito!"
        else
            render plain: "No se puedo generar el cobro en PayPal."
        end
    end

    private
    def get_items_hash(orders)
        items = orders.map do |order|
            item = {}
            item[:name] = order.product.name
            item[:sku] = order.id.to_s
            item[:price] = order.price.to_s
            item[:currency] = 'USD'
            item[:quantity] = order.quantity
            item
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
  end
  
  def create
    @product = Product.find(params[:product_id])
    @comment = Comment.new(content:params[:comment][:content], user: current_user)
    # @comment = @product.comments.create(params[:comment].permit(:comment))
    # @product.comments << @comment
    @comment.product = @product
         #@comment.save
         # redirect_to @post
    # @comment = comment.new(comment_params)
 
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders.cart
    @total = @orders.get_total

  end
  
  def create
    p = Product.find(params[:product_id])
    o = Order.find_or_create_by(user: current_user, product: p, payed: false, price: p.price)
    o.quantity += 1

    if o.save
      redirect_to products_path, notice: "El producto ha sido agregado al carro."
    else
      redirect_to products_path, alert: "El producto NO ha sido agregado al carro"
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path , notice: 'El carro se ha vaciado.'
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments
    @comment = Comment.new
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/billings/index.html.erb
<div class= 'container'>
    <% @billings.each do |billing|%>
      <p> <%= billing.amount %> </p>
      <hr>
    <% billing.orders.each do |order| %>
      <p><%= order.product.name %><p>
    <% end %>
  <% end %>
</div>
  

app/views/comments/_comment.html.erb
<td> <%= @comment.content %> </td>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$('#comments1').prepend('<%= j render @comment %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NovapartsStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
  <nav class="navbar sticky-top navbar-expand-lg navbar navbar-dark bg-primary">
  
  <a class="navbar-brand" href="#">NOVAPARTS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/products"> Home <span class="sr-only">(current)</span></a>
      </li>
  
      <li class="nav-item">
        <a class="nav-link" href="#"> Catalogo de productos  </a>
      </li>
    
      <ul class="nav navbar-nav navbar-right ">
        <% if user_signed_in? %>
          <li > <%= link_to  "Salir", destroy_user_session_path, method: :delete, class: 'nav-link' %> </li>
        <% else %>
        <li> <%=link_to "Iniciar sesion", new_user_session_path, class: 'nav-link' %> </li>
        <li> <%=link_to "Registrarse", new_user_registration_path, class: 'nav-link' %> </li>
        <% end %>
      </ul>
      
      <ul class="navbar-nav">
        <li class="nav-item active">
          <% if current_user !=nil%>
            <a class="nav-link" href="#">Hola: <%= current_user.email %> </a>
          <% end %>
        </li>
      </ul>
    </ul>
  </div>
</nav>
    <div class = 'container'> 
      
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    <div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <% if @orders.count > 0 %>
    <table class="table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Valor</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
        <% @orders.each do |order| %>
    <tr>
        <td> <%= order.product.name%> </td>
        <td> <%= order.product.price %> </td>
        <td> <%= order.quantity %> </td>
        <td> <%= order.quantity * order.product.price %> </td>
    </tr>
    <% end %>
    <tr class="table-dark">
      <td></td>
      <td></td>
      <td><strong>Total de la compra:</strong></td>
      <td><strong><%= @total %></strong></td>
      </tr>
    </tbody>
  </table>

  <%= link_to  "Vaciar carro", clean_orders_path %>
  <%= link_to 'Confirmar compra', pre_pay_billings_path, class: 'btn btn-success float-right' %> 

   <% else %>
    <p>No tienes productos en tu carro de compra.</p>
  <% end %>

</div>

app/views/products/_form.html.erb
<div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

app/views/products/index.html.erb
<h1>Productos</h1>

<%= link_to  "Ver carro", orders_path %>

<div class="container">
  <div class="row">
    <% @products.each_slice(3) do |row| %>
      <% row.each do |product| %>
        <div class='col-md-3' >
          <div class='card col-md-12 product_card'> 
            <%= image_tag product.photo, class: 'card-img-top' %>
              <div class="card-body">
                <h6 class="card-title"><%= product.sku %></h6>
                <h3 class="card-title"><%= product.name %></h3>
                <h5 class="card-title"><%= product.brand %></h5>
                <h5 class="card-title"><%= product.version %></ h5>
                <h5 class="card-title"><%= product.category %></   h5>
                <h5 class="card-title"><%= product.price %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%#product.name %></h6>
                <td> <%= button_to "Agregar al carro",product_orders_path(product), class:"btn btn-primary" %></td>
                <td> <%= link_to "Detalles", product_path(product), class:"btn btn-success" %></td>

              </div>
          </div>
        </div>
      <% end %>
    <div class="w-100" style="margin-top:20px;"> </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<%= form_with(model: [@product, Comment.new]) do |form| %>
 <% if @comment.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
     <ul>
     <% @comment.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
   <%= form.label :Comentario %>
   <%= form.text_area :content %>
 </div>
 <div class="actions">
   <%= form.submit %>
 </div>
<% end %>

<h3> Comentarios del producto <h3>

<table>
   <thead>
      <tr>
        <th>Comentarios</th>
        <th colspan="3"></th>
      <tr>
   </thead>

   <tbody>
        <tr id="comments1">
          <% @product.comments.each do |comment| %>
            <td><%= comment.content %></td> 
          <% end %>
        </tr>
        
   </tbody>
</table>